<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Commune;
use App\Models\Wilaya;

class CommuneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $communes = [
            'DZ-01' => [
                ['Adrar', 'أدرار'],
                ['Tamest', 'تامست'],
                ['Charouine', 'شروين'],
                ['Reggane', 'رقان'],
                ['Inozghmir', 'انوزغمير'],
                ['Tit', 'تيط'],
                ['Ksar Kaddour', 'قصر قدور'],
                ['Tsabit', 'تسابيت'],
                ['Timimoun', 'تيميمون'],
                ['Ouled Said', 'أولاد سعيد'],
                ['Zaouiet Kounta', 'زاوية كنتة'],
                ['Aoulef', 'أولف'],
                ['Timokten', 'تيموكتن'],
                ['Tamentit', 'تامنطيط'],
                ['Fenoughil', 'فنوغيل'],
                ['Tinerkouk', 'تنركوك'],
                ['Deldoul', 'دلدول'],
                ['Sali', 'سالي'],
                ['Akabli', 'أقبلي'],
                ['Metarfa', 'المطارفة'],
                ['Ouled Ahmed Timmi', 'أولاد أحمد تيمي'],
                ['Bouda', 'بودة'],
                ['Aougrout', 'أوقروت'],
                ['Talmine', 'تالمين'],
                ['Bordj Badji Mokhtar', 'برج باجي مختار'],
                ['Sebaa', 'السبع'],
                ['Ouled Aissa', 'أولاد عيسى'],
                ['Timiaouine', 'تيمياوين'],
            ],

            'DZ-02' => [
                ['Chlef', 'الشلف'],
                ['Tenes', 'تنـس'],
                ['Benairia', 'بنارية'],
                ['El Karimia', 'الكريمية'],
                ['Tadjna', 'تاجنة'],
                ['Taougrite', 'تاوقريت'],
                ['Beni Haoua', 'بني حواء'],
                ['Sobha', 'الصبحة'],
                ['Harchoun', 'حرشون'],
                ['Ouled Fares', 'أولاد فارس'],
                ['Sidi Akacha', 'سيدي عكاشة'],
                ['Boukadir', 'بوقادير'],
                ['Beni Rached', 'بني راشد'],
                ['Talassa', 'تلعصة'],
                ['Herenfa', 'هرنفة'],
                ['Oued Goussine', 'وادي قوسين'],
                ['Dahra', 'الظهرة'],
                ['Ouled Abbes', 'أولاد عباس'],
                ['Sendjas', 'السنجاس'],
                ['Zeboudja', 'الزبوجة'],
                ['Oued Sly', 'وادي سلي'],
                ['Abou El Hassen', 'أبو الحسن'],
                ['El Marsa', 'المرسى'],
                ['Chettia', 'الشطية'],
                ['Sidi Abderrahmane', 'سيدي عبد الرحمن'],
                ['Moussadek', 'المصدق'],
                ['El Hadjadj', 'الحجاج'],
                ['Labiod Medjadja', 'الأبيض مجاجة'],
                ['Oued Fodda', 'وادي الفضة'],
                ['Ouled Ben Abdelkader', 'أولاد بن عبد القادر'],
                ['Bouzghaia', 'بوزغاية'],
                ['Ain Merane', 'عين مران'],
                ['Oum Drou', 'أم دروع'],
                ['Breira', 'بريرة'],
                ['Ben Boutaleb', 'بن بوطالب'],
            ],

            'DZ-03' => [
                ['Laghouat', 'الأغواط'],
                ['Ksar El Hirane', 'قصر الحيران'],
                ['Benacer Ben Chohra', 'بن ناصر بن شهرة'],
                ['Sidi Makhlouf', 'سيدي مخلوف'],
                ['Hassi Delaa', 'حاسي الدلاعة'],
                ['Hassi R Mel', 'حاسي الرمل'],
                ['Ain Mahdi', 'عين ماضي'],
                ['Tadjmout', 'تاجموت'],
                ['Kheneg', 'الخنق'],
                ['Gueltat Sidi Saad', 'قلتة سيدي سعد'],
                ['Ain Sidi Ali', 'عين سيدي علي'],
                ['Beidha', 'البيضاء'],
                ['Brida', 'بريدة'],
                ['El Ghicha', 'الغيشة'],
                ['Hadj Mechri', 'الحاج مشري'],
                ['Sebgag', 'سبقاق'],
                ['Taouiala', 'تاويالة'],
                ['Tadjrouna', 'تاجرونة'],
                ['Aflou', 'أفلو'],
                ['El Assafia', 'العسافية'],
                ['Oued Morra', 'وادي مرة'],
                ['Oued M Zi', 'وادي مزي'],
                ['El Haouaita', 'الحويطة'],
                ['Sidi Bouzid', 'سيدي بوزيد'],
            ],

            'DZ-04' => [
                ['Oum El Bouaghi', 'أم البواقي'],
                ['Ain Beida', 'عين البيضاء'],
                ['Ainmlila', 'عين مليلة'],
                ['Behir Chergui', 'بحير الشرقي'],
                ['El Amiria', 'العامرية'],
                ['Sigus', 'سيقوس'],
                ['El Belala', 'البلالة'],
                ['Ain Babouche', 'عين بابوش'],
                ['Berriche', 'بريش'],
                ['Ouled Hamla', 'أولاد حملة'],
                ['Dhala', 'الضحالة'],
                ['Ain Kercha', 'عين كرشة'],
                ['Hanchir Toumghani', 'هنشير تومغاني'],
                ['El Djazia', 'الجازية'],
                ['Ain Diss', 'عين الديس'],
                ['Fkirina', 'فكيرينة'],
                ['Souk Naamane', 'سوق نعمان'],
                ['Zorg', 'الزرق'],
                ['El Fedjoudj Boughrar', 'الفجوج بوغرارة'],
                ['Ouled Zouai', 'أولاد زواي'],
                ['Bir Chouhada', 'بئر الشهداء'],
                ['Ksar Sbahi', 'قصر الصباحي'],
                ['Oued Nini', 'وادي نيني'],
                ['Meskiana', 'مسكيانة'],
                ['Ain Fekroune', 'عين فكرون'],
                ['Rahia', 'الراشية'],
                ['Ain Zitoun', 'عين الزيتون'],
                ['Ouled Gacem', 'أولاد قاسم'],
                ['El Harmilia', 'الحرملية'],
            ],

            'DZ-05' => [
                ['Batna', 'باتنة'],
                ['Ghassira', 'غسيرة'],
                ['Maafa', 'معافة'],
                ['Merouana', 'مروانة'],
                ['Seriana', 'سريانة'],
                ['Menaa', 'منعة'],
                ['El Madher', 'المعذر'],
                ['Tazoult', 'تازولت'],
                ['Ngaous', 'نقاوس'],
                ['Guigba', 'قيقبة'],
                ['Inoughissen', 'إينوغيسن'],
                ['Ouyoun El Assafir', 'عيون العصافير'],
                ['Djerma', 'جرمة'],
                ['Bitam', 'بيطام'],
                ['Metkaouak', 'متكعوك'],
                ['Arris', 'أريس'],
                ['Kimmel', 'كيميل'],
                ['Tilatou', 'تيلاطو'],
                ['Ain Djasser', 'عين جاسر'],
                ['Ouled Selam', 'أولاد سلام'],
                ['Tigherghar', 'تيغرغار'],
                ['Ain Yagout', 'عين ياقوت'],
                ['Fesdis', 'فسديس'],
                ['Sefiane', 'سفيان'],
                ['Rahbat', 'الرحبات'],
                ['Tighanimine', 'تيغانمين'],
                ['Lemsane', 'اللمسان'],
                ['Ksar Belezma', 'قصر بيليزما'],
                ['Seggana', 'سقانة'],
                ['Ichmoul', 'إشمول'],
                ['Foum Toub', 'فم الطوب'],
                ['Beni Foudhala El Hakania', 'بني فوضالة الحاكنية'],
                ['Oued El Ma', 'وادي الماء'],
                ['Talkhamt', 'تلقمت'],
                ['Bouzina', 'بوزينة'],
                ['Chemora', 'شمورة'],
                ['Oued Chaaba', 'وادي الشعبة'],
                ['Taxlent', 'تاكسلنت'],
                ['Gosbat', 'قصر البات'],
                ['Ouled Aouf', 'أولاد عوف'],
                ['Boumagueur', 'بومقر'],
                ['Barika', 'بريكة'],
                ['Djezzar', 'الجزار'],
                ['Tkout', 'تكوت'],
                ['Ain Touta', 'عين التوتة'],
                ['Hidoussa', 'حيدوسة'],
                ['Teniet El Abed', 'ثنية العابد'],
                ['Oued Taga', 'وادي الطاقة'],
                ['Ouled Fadel', 'أولاد فاضل'],
                ['Timgad', 'تيمقاد'],
                ['Ras El Aioun', 'رأس العيون'],
                ['Chir', 'شير'],
                ['Ouled Si Slimane', 'أولاد سيدي سليمان'],
                ['Zanat El Beida', 'زانة البيضاء'],
                ['Amdoukal', 'أمدوكل'],
                ['Ouled Ammar', 'أولاد عمار'],
                ['El Hassi', 'الحاسي'],
                ['Lazrou', 'لازرو'],
                ['Boumia', 'بوميا'],
                ['Boulhilat', 'بولحيلات'],
                ['Larbaa', 'الأربعاء'],
            ],

            'DZ-06' => [
                ['Bejaia', 'بجاية'],
                ['Amizour', 'أميزور'],
                ['Ferraoun', 'فرعون'],
                ['Taourirt Ighil', 'تاوريرت إغيل'],
                ['Chelata', 'شلاطة'],
                ['Tamokra', 'تامقرة'],
                ['Timzrit', 'تيمزريت'],
                ['Souk El Thenine', 'سوق الاثنين'],
                ['Mcisna', 'مسيسنة'],
                ['Thinabdher', 'ثينبدار'],
                ['Tichi', 'تيشي'],
                ['Semaoun', 'سمعون'],
                ['Kendira', 'كنديرة'],
                ['Tifra', 'تيفرة'],
                ['Ighram', 'إغرم'],
                ['Amalou', 'أمالو'],
                ['Ighil Ali', 'إغيل علي'],
                ['Ifelain Ilmathen', 'إيفلاين إلماثن'],
                ['Toudja', 'توجة'],
                ['Darguina', 'درقينة'],
                ['Sidi Ayad', 'سيدي عياد'],
                ['Aokas', 'أوقاس'],
                ['Beni Djellil', 'بني جليل'],
                ['Adekar', 'آدكار'],
                ['Akbou', 'أقبو'],
                ['Seddouk', 'صدوق'],
                ['Tazmalt', 'تازملت'],
                ['Ait Rizine', 'آيت رزين'],
                ['Chemini', 'شميني'],
                ['Souk Oufella', 'سوق أوفلة'],
                ['Taskriout', 'تاسكريوت'],
                ['Tibane', 'تيبان'],
                ['Tala Hamza', 'تالة حمزة'],
                ['Barbacha', 'برباشة'],
                ['Beni Ksila', 'بني كسيلة'],
                ['Ouzallaguen', 'أوزلاقن'],
                ['Bouhamza', 'بوحمزة'],
                ['Beni Melikeche', 'بني مليكش'],
                ['Sidi Aich', 'سيدي عيش'],
                ['El Kseur', 'القصر'],
                ['Melbou', 'ملبو'],
                ['Akfadou', 'أكفادو'],
                ['Leflaye', 'لفلاي'],
                ['Kherrata', 'خراطة'],
                ['Draa Kaid', 'ذراع القايد'],
                ['Tamridjet', 'تامريجت'],
                ['Ait Smail', 'آيت اسماعيل'],
                ['Boukhelifa', 'بوخليفة'],
                ['Tizi Nberber', 'تيزي نبربر'],
                ['Beni Maouch', 'بني معوش'],
                ['Oued Ghir', 'وادي غير'],
                ['Boudjellil', 'بوجليل'],
            ],

            'DZ-07' => [
                ['Biskra', 'بسكرة'],
                ['Oumache', 'أوماش'],
                ['Branis', 'برانيس'],
                ['Chetma', 'شتمة'],
                ['Ouled Djellal', 'أولاد جلال'],
                ['Ras El Miaad', 'رأس الميعاد'],
                ['Besbes', 'بسباس'],
                ['Sidi Khaled', 'سيدي خالد'],
                ['Doucen', 'الدوسن'],
                ['Ech Chaiba', 'الشعيبة'],
                ['Sidi Okba', 'سيدي عقبة'],
                ['Mchouneche', 'مشونش'],
                ['El Haouch', 'الحوش'],
                ['Ain Naga', 'عين الناقة'],
                ['Zeribet El Oued', 'زريبة الوادي'],
                ['El Feidh', 'الفيض'],
                ['El Kantara', 'القنطرة'],
                ['Ain Zaatout', 'عين زعطوط'],
                ['El Outaya', 'الوطاية'],
                ['Djemorah', 'جمورة'],
                ['Tolga', 'طولقة'],
                ['Lioua', 'ليوة'],
                ['Lichana', 'ليشانة'],
                ['Ourlal', 'أورلال'],
                ['Mlili', 'مليلي'],
                ['Foughala', 'فوغالة'],
                ['Bordj Ben Azzouz', 'برج بن عزوز'],
                ['Meziraa', 'ميزرانة'],
                ['Bouchagroun', 'بوشقرون'],
                ['Mekhadma', 'المخادمة'],
                ['El Ghrous', 'الغروس'],
                ['El Hadjab', 'الحجّاب'],
                ['Khanguet Sidinadji', 'خنقة سيدي ناجي'],
            ],

            'DZ-08' => [
                ['Bechar', 'بشار'],
                ['Erg Ferradj', 'عرق فراج'],
                ['Ouled Khoudir', 'أولاد خضير'],
                ['Meridja', 'مريجة'],
                ['Timoudi', 'تيمودي'],
                ['Lahmar', 'لحمر'],
                ['Beni Abbes', 'بني عباس'],
                ['Beni Ikhlef', 'بني يخلف'],
                ['Mechraa Houari B', 'مشرع هواري بومدين'],
                ['Kenedsa', 'قنادسة'],
                ['Igli', 'إقلي'],
                ['Tabalbala', 'تبلبالة'],
                ['Taghit', 'تاغيت'],
                ['El Ouata', 'الوَطَة'],
                ['Boukais', 'بوقايس'],
                ['Mogheul', 'موغل'],
                ['Abadla', 'العبادلة'],
                ['Kerzaz', 'كرزاز'],
                ['Ksabi', 'القصابي'],
                ['Tamtert', 'تامترت'],
                ['Beni Ounif', 'بني ونيف'],
            ],

            'DZ-09' => [
                ['Blida', 'البليدة'],
                ['Chebli', 'شفة'],
                ['Bouinan', 'بوعينان'],
                ['Oued El Alleug', 'وادي العلايق'],
                ['Ouled Yaich', 'أولاد يعيش'],
                ['Chrea', 'الشريعة'],
                ['El Affroun', 'العفرون'],
                ['Chiffa', 'الشفة'],
                ['Hammam Melouane', 'حمام ملوان'],
                ['Ben Khlil', 'بن خليل'],
                ['Soumaa', 'الصومعة'],
                ['Mouzaia', 'موزاية'],
                ['Souhane', 'سوحان'],
                ['Meftah', 'مفتاح'],
                ['Ouled Selama', 'أولاد سلامة'],
                ['Boufarik', 'بوفاريك'],
                ['Larbaa', 'الأربعاء'],
                ['Oued Djer', 'وادي جر'],
                ['Beni Tamou', 'بني تامو'],
                ['Bouarfa', 'بوعرفة'],
                ['Beni Mered', 'بني مراد'],
                ['Bougara', 'بوقرة'],
                ['Guerrouaou', 'قرواو'],
                ['Ain Romana', 'عين الرمانة'],
                ['Djebabra', 'جبابرة'],
            ],

            'DZ-10' => [
                ['Bouira', 'البويرة'],
                ['El Asnam', 'الأصنام'],
                ['Guerrouma', 'قرومة'],
                ['Souk El Khemis', 'سوق الخميس'],
                ['Kadiria', 'القادرية'],
                ['Hanif', 'حنيف'],
                ['Dirah', 'ديرة'],
                ['Ait Laaziz', 'آيت لعزيز'],
                ['Taghzout', 'تاغزوت'],
                ['Raouraoua', 'راوروة'],
                ['Mezdour', 'مزغور'],
                ['Haizer', 'حيزر'],
                ['Lakhdaria', 'الأخضرية'],
                ['Maala', 'المعلة'],
                ['El Hachimia', 'الهاشمية'],
                ['Aomar', 'عمر'],
                ['Chorfa', 'الشرفاء'],
                ['Bordj Oukhriss', 'برج أوخريص'],
                ['El Adjiba', 'العجيبة'],
                ['El Hakimia', 'الحكيمية'],
                ['El Khebouzia', 'الخبوذية'],
                ['Ahl El Ksar', 'أهل القصر'],
                ['Bouderbala', 'بودربالة'],
                ['Zbarbar', 'زبربر'],
                ['Ain El Hadjar', 'عين الحجار'],
                ['Djebahia', 'جباحية'],
                ['Aghbalou', 'أغبالو'],
                ['Taguedit', 'تاقيديت'],
                ['Ain Turk', 'عين الترك'],
                ['Saharidj', 'سحاريج'],
                ['Dechmia', 'دشمية'],
                ['Ridane', 'ريدان'],
                ['Bechloul', 'بشلول'],
                ['Boukram', 'بوكرم'],
                ['Ain Bessam', 'عين بسام'],
                ['Bir Ghbalou', 'بئر غبالو'],
                ['Mchedallah', 'مشد الله'],
                ['Sour El Ghozlane', 'سور الغزلان'],
                ['Maamora', 'معمورة'],
                ['Ouled Rached', 'أولاد راشد'],
                ['Ain Laloui', 'عين العلوي'],
                ['Hadjera Zerga', 'الحجرة الزرقاء'],
                ['Ath Mansour', 'آيت منصور'],
                ['El Mokrani', 'المقراني'],
                ['Oued El Berdi', 'وادي البردي'],
            ],

            'DZ-11' => [
                ['Tamanghasset', 'تمنراست'],
                ['Abalessa', 'أبلسة'],
                ['In Ghar', 'عين غار'],
                ['In Guezzam', 'عين قزام'],
                ['Idles', 'إيدلس'],
                ['Tazouk', 'طازروك'],
                ['Tinzaouatine', 'تين زاوتين'],
                ['In Salah', 'عين صالح'],
                ['In Amguel', 'عين أمقل'],
                ['Foggaret Ezzaouia', 'فقارة الزاوية'],
            ],
            
            'DZ-12' => [
                ['Tebessa', 'تبسة'],
                ['Bir El Ater', 'بئر العاتر'],
                ['Cheria', 'الشريعة'],
                ['Stah Guentis', 'سطاح قنطيس'],
                ['El Aouinet', 'العوينات'],
                ['Lahouidjbet', 'لحويجبات'],
                ['Safsaf El Ouesra', 'صفصاف الوسرة'],
                ['Hammamet', 'حمامات'],
                ['Negrine', 'نقرين'],
                ['Bir El Mokadem', 'بئر المقدم'],
                ['El Kouif', 'الكويف'],
                ['Morsott', 'مرسط'],
                ['El Ogla', 'العقلة'],
                ['Bir Dheheb', 'بئر الذهب'],
                ['El Ogla El Malha', 'العقلة الملحة'],
                ['Gorriguer', 'قريقر'],
                ['Bekkaria', 'البكارية'],
                ['Boukhadra', 'بوخضرة'],
                ['Ouenza', 'ونزة'],
                ['El Ma El Biodh', 'الماء البيض'],
                ['Oum Ali', 'أم علي'],
                ['Thlidjene', 'ثليجان'],
                ['Ain Zerga', 'عين الزرقاء'],
                ['El Meridj', 'المريج'],
                ['Boulhaf Dyr', 'بولهاف الدير'],
                ['Bedjene', 'الباجن'],
                ['El Mazeraa', 'المزيرعة'],
                ['Ferkane', 'فرقان'],
            ],

            'DZ-13' => [
                ['Tlemcen', 'تلمسان'],
                ['Beni Mester', 'بني مستر'],
                ['Ain Tallout', 'عين تلوت'],
                ['Remchi', 'رمشي'],
                ['El Fehoul', 'الفحول'],
                ['Sabra', 'صبرة'],
                ['Ghazaouet', 'الغزوات'],
                ['Souani', 'السواني'],
                ['Djebala', 'جبالة'],
                ['El Gor', 'الغور'],
                ['Oued Chouly', 'واد الشولي'],
                ['Ain Fezza', 'عين فزة'],
                ['Ouled Mimoun', 'أولاد ميمون'],
                ['Amieur', 'عمير'],
                ['Ain Youcef', 'عين يوسف'],
                ['Zenata', 'زناتة'],
                ['Beni Snous', 'بني سنوس'],
                ['Bab El Assa', 'باب العسة'],
                ['Dar Yaghmouracene', 'دار يغمراسن'],
                ['Fellaoucene', 'فلاوسن'],
                ['Azails', 'أزايل'],
                ['Sebbaa Chioukh', 'سبعة شيوخ'],
                ['Terni Beni Hediel', 'تيرني بني هديل'],
                ['Bensekrane', 'بن سكران'],
                ['Ain Nehala', 'عين نهالة'],
                ['Hennaya', 'الهناية'],
                ['Maghnia', 'مغنية'],
                ['Hammam Boughrara', 'حمام بوغرارة'],
                ['Souahlia', 'السواحلية'],
                ['Msirda Fouaga', 'مسردة فوقة'],
                ['Ain Fetah', 'عين فتاح'],
                ['El Aricha', 'العريشة'],
                ['Souk Thlata', 'سوق الثلاثاء'],
                ['Sidi Abdelli', 'سيدي عبدلي'],
                ['Sebdou', 'سبدو'],
                ['Beni Ouarsous', 'بني ورسوس'],
                ['Sidi Medjahed', 'سيدي مجاهد'],
                ['Beni Boussaid', 'بني بوسعيد'],
                ['Marsa Ben Mhidi', 'مرسى بن مهيدي'],
                ['Nedroma', 'ندرمه'],
                ['Sidi Djillali', 'سيدي الجيلالي'],
                ['Beni Bahdel', 'بني بهدل'],
                ['El Bouihi', 'البويهي'],
                ['Honaine', 'هنين'],
                ['Tianet', 'تيانات'],
                ['Ouled Riyah', 'أولاد رياح'],
                ['Bouhlou', 'بوحلو'],
                ['Souk El Khemis', 'سوق الخميس'],
                ['Ain Ghoraba', 'عين غرابة'],
                ['Chetouane', 'شطوان'],
                ['Mansourah', 'المنصورة'],
                ['Beni Semiel', 'بني سميل'],
                ['Ain Kebira', 'عين الكبيرة'],
            ],

            'DZ-14' => [
                ['Tiaret', 'تيارت'],
                ['Medroussa', 'مدروسة'],
                ['Ain Bouchekif', 'عين بوشقيف'],
                ['Sidi Ali Mellal', 'سيدي علي ملال'],
                ['Ain Zarit', 'عين زاريت'],
                ['Ain Deheb', 'عين الذهب'],
                ['Sidi Bakhti', 'سيدي بختي'],
                ['Medrissa', 'مدريسة'],
                ['Zmalet El Emir Aek', 'زمالة الأمير عبد القادر'],
                ['Madna', 'مادنة'],
                ['Sebt', 'سبع'],
                ['Mellakou', 'ملاكو'],
                ['Dahmouni', 'دهموني'],
                ['Rahouia', 'رحوية'],
                ['Mahdia', 'مهدية'],
                ['Sougueur', 'سوقهر'],
                ['Sidi Abdelghani', 'سيدي عبد الغاني'],
                ['Ain El Hadid', 'عين الحديد'],
                ['Ouled Djerad', 'أولاد جراد'],
                ['Naima', 'نعيمة'],
                ['Meghila', 'مغيلة'],
                ['Guertoufa', 'قرطوفة'],
                ['Sidi Hosni', 'سيدي حسني'],
                ['Djillali Ben Amar', 'جيلالي بن عمار'],
                ['Sebaine', 'سبعين'],
                ['Tousnina', 'توسنينة'],
                ['Frenda', 'فرندة'],
                ['Ain Kermes', 'عين كرمس'],
                ['Ksar Chellala', 'قصر الشلالة'],
                ['Rechaiga', 'رشايقة'],
                ['Nadorah', 'ناظورة'], // Note: Might be ناظورة, but based on knowledge, it's ناظورة
                ['Tagdemt', 'تاقدمت'],
                ['Oued Lilli', 'وادي ليلي'],
                ['Mechraa Safa', 'مشروع الصفا'],
                ['Hamadia', 'حمادية'],
                ['Chehaima', 'شحيمة'],
                ['Takhemaret', 'تخمرت'],
                ['Sidi Abderrahmane', 'سيدي عبد الرحمن'],
                ['Serghine', 'سرغين'],
                ['Bougara', 'بوغرة'],
                ['Faidja', 'فايجة'],
                ['Tidda', 'تيدة'],
            ],

            'DZ-15' => [
                ['Tizi Ouzou', 'تيزي وزو'],
                ['Ain El Hammam', 'عين الحمام'],
                ['Akbil', 'أقبيل'],
                ['Freha', 'فريحة'],
                ['Souamaa', 'سوامع'],
                ['Mechtrass', 'مشتراس'],
                ['Irdjen', 'إيرجان'],
                ['Timizart', 'تيميزارت'],
                ['Makouda', 'ماكودة'],
                ['Draa El Mizan', 'ذراع الميزان'],
                ['Tizi Ghenif', 'تيزي غنيف'],
                ['Bounouh', 'بونوح'],
                ['Ait Chaffaa', 'أيت شفعة'],
                ['Frikat', 'فريقات'],
                ['Beni Aissi', 'بني عيسي'],
                ['Beni Zmenzer', 'بني زمزر'],
                ['Iferhounene', 'إفرحونن'],
                ['Azazga', 'عزازقة'],
                ['Iloula Oumalou', 'إيلولا أومالو'],
                ['Yakouren', 'ياكورن'],
                ['Larba Nait Irathen', 'لعربا ناث إيراثن'],
                ['Tizi Rached', 'تيزي راشد'],
                ['Zekri', 'زكري'],
                ['Ouaguenoun', 'واقنون'],
                ['Ain Zaouia', 'عين الزاوية'],
                ['Mkira', 'مكيرة'],
                ['Ait Yahia', 'أيت يحيى'],
                ['Ait Mahmoud', 'أيت محمود'],
                ['Maatka', 'معاتقة'],
                ['Ait Boumehdi', 'أيت بومهدي'],
                ['Abi Youcef', 'أبي يوسف'],
                ['Beni Douala', 'بني دوالة'],
                ['Illilten', 'إيليلتن'],
                ['Bouzguen', 'بوزقن'],
                ['Ait Aggouacha', 'أيت أقواشة'],
                ['Ouadhia', 'واضية'],
                ['Azzefoun', 'أزفون'],
                ['Tigzirt', 'تيقزيرت'],
                ['Ait Aissa Mimoun', 'أيت عيسى ميمون'],
                ['Boghni', 'بوغني'],
                ['Ifigha', 'إيفيغاء'],
                ['Ait Oumalou', 'أيت أومالو'],
                ['Tirmitine', 'تيرميتين'],
                ['Akerrou', 'أقرو'],
                ['Yatafen', 'ياتفن'],
                ['Beni Ziki', 'بني زيكي'],
                ['Draa Ben Khedda', 'ذراع بن خدة'],
                ['Ouacif', 'واسيف'],
                ['Idjeur', 'إيجار'],
                ['Mekla', 'مقلع'],
                ['Tizi Nthlata', 'تيزي نثلاثة'],
                ['Beni Yenni', 'بني يني'],
                ['Aghrib', 'أغريب'],
                ['Iflissen', 'إيفليسين'],
                ['Boudjima', 'بوجيمة'],
                ['Ait Yahia Moussa', 'أيت يحيى موسى'],
                ['Souk El Thenine', 'سوق الإثنين'],
                ['Ait Khelil', 'أيت خليلي'],
                ['Sidi Naamane', 'سيدي نعمان'],
                ['Iboudraren', 'إيبودرارن'],
                ['Aghni Goughran', 'أغني غوغران'],
                ['Mizrana', 'ميزرانة'],
                ['Imsouhal', 'إمسوهال'],
                ['Tadmait', 'تادمايت'],
                ['Ait Bouadou', 'أيت بواضو'],
                ['Assi Youcef', 'أسي يوسف'],
                ['Ait Toudert', 'أيت تودرت'],
            ],

            'DZ-16' => [
                ['Alger Centre', 'الجزائر الوسطى'],
                ['Sidi Mhamed', 'سيدي أمحمد'],
                ['El Madania', 'المدنية'],
                ['Hamma Anassers', 'الحامة العناصر'],
                ['Bab El Oued', 'باب الوادي'],
                ['Bologhine Ibn Ziri', 'بولوغين ابن زيري'],
                ['Casbah', 'القصبة'],
                ['Oued Koriche', 'وادي قريش'],
                ['Bir Mourad Rais', 'بئر مراد رايس'],
                ['El Biar', 'الأبيار'],
                ['Bouzareah', 'بوزريعة'],
                ['Birkhadem', 'بئر خادم'],
                ['El Harrach', 'الحراش'],
                ['Baraki', 'براقي'],
                ['Oued Smar', 'وادي السمار'],
                ['Bourouba', 'بوروبة'],
                ['Hussein Dey', 'حسين داي'],
                ['Kouba', 'القوبة'],
                ['Bachedjerah', 'باش جراح'],
                ['Dar El Beida', 'دار البيضاء'],
                ['Bab Azzouar', 'باب الزوار'],
                ['Ben Aknoun', 'بن عكنون'],
                ['Dely Ibrahim', 'دالي إبراهيم'],
                ['Bains Romains', 'الحمامات الرومانية'],
                ['Rais Hamidou', 'رأس حميدو'],
                ['Djasr Kasentina', 'جسر قسنطينة'],
                ['El Mouradia', 'المرادية'],
                ['Hydra', 'حيدرا'],
                ['Mohammadia', 'المحمدية'],
                ['Bordj El Kiffan', 'برج الكيفان'],
                ['El Magharia', 'المغارية'],
                ['Beni Messous', 'بني مسوس'],
                ['Les Eucalyptus', 'الأوكاليبتوس'],
                ['Birtouta', 'بئر توتة'],
                ['Tassala El Merdja', 'تسالة المرجة'],
                ['Ouled Chebel', 'أولاد الشبل'],
                ['Sidi Moussa', 'سيدي موسى'],
                ['Ain Taya', 'عين طاية'],
                ['Bordj El Bahri', 'برج البحري'],
                ['Marsa', 'المرسى'],
                ['Haraoua', 'هراوة'],
                ['Rouiba', 'رويبة'],
                ['Reghaia', 'الرغاية'],
                ['Ain Benian', 'عين بنيان'],
                ['Staoueli', 'سطاوالي'],
                ['Zeralda', 'زرالدة'],
                ['Mahelma', 'محالمة'],
                ['Rahmania', 'الرحمانية'],
                ['Souidania', 'السويدانية'],
                ['Cheraga', 'الشراقة'],
                ['Ouled Fayet', 'أولاد فايت'],
                ['El Achour', 'العاشور'],
                ['Draria', 'دراريا'],
                ['Douera', 'الدويرة'],
                ['Baba Hassen', 'بابا حسن'],
                ['Khracia', 'الخراسية'],
                ['Saoula', 'سحولة'],
                ],
                'DZ-17' => [
                ['Djelfa', 'الجلفة'],
                ['Moudjebara', 'مجبارة'],
                ['El Guedid', 'القديد'],
                ['Hassi Bahbah', 'حاسي بحبح'],
                ['Ain Maabed', 'عين معبد'],
                ['Sed Rahal', 'سد الرحال'],
                ['Feidh El Botma', 'فيض البطمة'],
                ['Birine', 'البيرين'],
                ['Bouira Lahdeb', 'بويرة الأحدب'],
                ['Zaccar', 'زكار'],
                ['El Khemis', 'الخميس'],
                ['Sidi Baizid', 'سيدي بايزيد'],
                ['Mliliha', 'مليليحة'],
                ['El Idrissia', 'الإدريسية'],
                ['Douis', 'دويس'],
                ['Hassi El Euch', 'حاسي العش'],
                ['Messaad', 'مسعد'],
                ['Guettara', 'قطارة'],
                ['Sidi Ladjel', 'سيدي لعجل'],
                ['Had Sahary', 'حد الصحاري'],
                ['Guernini', 'قرنيني'],
                ['Selmana', 'سلمانة'],
                ['Ain Chouhada', 'عين الشهداء'],
                ['Oum Laadham', 'أم العظام'],
                ['Dar Chouikh', 'دار الشيوخ'],
                ['Charef', 'الشرف'],
                ['Beni Yacoub', 'بني يعقوب'],
                ['Zaafrane', 'زعفران'],
                ['Deldoul', 'دلدول'],
                ['Ain El Ibel', 'عين الإبل'],
                ['Ain Oussera', 'عين وسارة'],
                ['Benhar', 'بنهار'],
                ['Hassi Fedoul', 'حاسي فدول'],
                ['Amourah', 'عمورة'],
                ['Ain Fekka', 'عين فكة'],
                ['Tadmit', 'تادميت'],
            ],

            'DZ-18' => [
                ['Jijel', 'جيجل'],
                ['Erraguene', 'الرقان'],
                ['El Aouana', 'العوانة'],
                ['Ziamma Mansouriah', 'زيامة منصورية'],
                ['Taher', 'الطاهر'],
                ['Emir Abdelkader', 'أمير عبد القادر'],
                ['Chekfa', 'الشقفة'],
                ['Chahna', 'الشحنة'],
                ['El Milia', 'الميلية'],
                ['Sidi Maarouf', 'سيدي معروف'],
                ['Settara', 'السطارة'],
                ['El Ancer', 'العنصر'],
                ['Sidi Abdelaziz', 'سيدي عبد العزيز'],
                ['Kaous', 'قاوس'],
                ['Ghebala', 'غبالة'],
                ['Bouraoui Belhadef', 'بوراوي بلهادف'],
                ['Djmila', 'جيميلة'],
                ['Selma Benziada', 'سلمى بن زيادة'],
                ['Boussif Ouled Askeur', 'بوسيف أولاد عسكر'],
                ['El Kennar Nouchfi', 'القنار نوشفي'],
                ['Ouled Yahia Khadrouch', 'أولاد يحيى خضروش'],
                ['Boudria Beni Yadjis', 'بودريعة بني ياجيس'],
                ['Kemir Oued Adjoul', 'قمير وادي عجول'],
                ['Texena', 'تكسنة'],
                ['Djemaa Beni Habibi', 'جامعة بني حبيبي'],
                ['Bordj Taher', 'برج الطاهر'],
                ['Ouled Rabah', 'أولاد رابح'],
                ['Ouadjana', 'واجانة'],
            ],

            'DZ-19' => [
                ['Setif', 'سطيف'],
                ['Ain El Kebira', 'عين الكبيرة'],
                ['Beni Aziz', 'بني عزيز'],
                ['Ouled Sidi Ahmed', 'أولاد سيدي أحمد'],
                ['Boutaleb', 'بوطالب'],
                ['Ain Roua', 'عين الروى'],
                ['Draa Kebila', 'درعة كبيلة'],
                ['Bir El Arch', 'بئر العرش'],
                ['Beni Chebana', 'بني شبانة'],
                ['Ouled Tebben', 'أولاد تبان'],
                ['Hamma', 'حمام'],
                ['Maaouia', 'معاوية'],
                ['Ain Legraj', 'عين الجراج'],
                ['Ain Abessa', 'عين عباسة'],
                ['Dehamcha', 'دهامشة'],
                ['Babor', 'بابور'],
                ['Guidjel', 'قجال'],
                ['Ain Lahdjar', 'عين لحجار'],
                ['Bousselam', 'بوسلام'],
                ['El Eulma', 'العلمة'],
                ['Djemila', 'جميلة'],
                ['Beni Ouartilane', 'بني ورتيلان'],
                ['Rosfa', 'الرصفة'],
                ['Ouled Addouane', 'أولاد عدوان'],
                ['Belaa', 'البلاعة'],
                ['Ain Arnat', 'عين أرنات'],
                ['Amoucha', 'عموشة'],
                ['Ain Oulmane', 'عين ولمان'],
                ['Beidha Bordj', 'بئيضة برج'],
                ['Bouandas', 'بواندس'],
                ['Bazer Sakhra', 'بازر صخرة'],
                ['Hammam Essokhna', 'حمام السخنة'],
                ['Mezloug', 'مزلوق'],
                ['Bir Haddada', 'بئر حدادة'],
                ['Serdj El Ghoul', 'سرج الغول'],
                ['Harbil', 'حربيل'],
                ['El Ouricia', 'العوريجة'],
                ['Tizi Nbechar', 'تيزي نبشار'],
                ['Salah Bey', 'صالح باي'],
                ['Ain Azal', 'عين أزال'],
                ['Guenzet', 'غنزات'],
                ['Talaifacene', 'تليفاثين'],
                ['Bougaa', 'بوقاعة'],
                ['Beni Fouda', 'بني فودة'],
                ['Tachouda', 'تاشودة'],
                ['Beni Mouhli', 'بني موحلي'],
                ['Ouled Sabor', 'أولاد صابر'],
                ['Guellal', 'غلال'],
                ['Ain Sebt', 'عين السبط'],
                ['Hammam Guergour', 'حمام قرقور'],
                ['Ait Naoual Mezada', 'عيت نوال مزادة'],
                ['Ksar El Abtal', 'قصر الأبطال'],
                ['Beni Hocine', 'بني حسين'],
                ['Ait Tizi', 'عيت تيزي'],
                ['Maouklane', 'ماوكلان'],
                ['Guelta Zerka', 'قلتة زرقاء'],
                ['Oued El Barad', 'وادي البراد'],
                ['Taya', 'تاية'],
                ['El Ouldja', 'العلجة'],
                ['Tella', 'تالة'],
            ],

            'DZ-20' => [
                ['Saida', 'سعيدة'],
                ['Doui Thabet', 'دوي ثابت'],
                ['Ain El Hadjar', 'عين الحجر'],
                ['Ouled Khaled', 'أولاد خالد'],
                ['Moulay Larbi', 'مولاي العربي'],
                ['Youb', 'يوب'],
                ['Hounet', 'هونت'],
                ['Sidi Amar', 'سيدي عمار'],
                ['Sidi Boubekeur', 'سيدي بوبكر'],
                ['El Hassasna', 'الحساسنة'],
                ['Maamora', 'المعمرة'],
                ['Sidi Ahmed', 'سيدي أحمد'],
                ['Ain Sekhouna', 'عين السخونة'],
                ['Ouled Brahim', 'أولاد إبراهيم'],
                ['Tircine', 'ترسين'],
                ['Ain Soltane', 'عين سلطان'],
            ],

            'DZ-21' => [
                ['Skikda', 'سكيكدة'],
                ['Ain Zouit', 'عين زويت'],
                ['El Hadaik', 'الحدائق'],
                ['Azzaba', 'عزابة'],
                ['Djendel Saadi Mohamed', 'جندل السعدي محمد'],
                ['Ain Cherchar', 'عين شرشار'],
                ['Bekkouche Lakhdar', 'بكوش لخضر'],
                ['Benazouz', 'بن عزوز'],
                ['Es Sebt', 'السبت'],
                ['Collo', 'القل'],
                ['Beni Zid', 'بني زيد'],
                ['Kerkera', 'الكركرة'],
                ['Ouled Attia', 'أولاد عطية'],
                ['Oued Zehour', 'وادي الزهور'],
                ['Zitouna', 'الزيتونة'],
                ['El Harrouch', 'الحروش'],
                ['Zerdazas', 'زردازة'],
                ['Ouled Hebaba', 'أولاد حبابة'],
                ['Sidi Mezghiche', 'سيدي مزغيش'],
                ['Emdjez Edchich', 'مجاز الدشيش'],
                ['Beni Oulbane', 'بني ولبان'],
                ['Ain Bouziane', 'عين بوزيان'],
                ['Ramdane Djamel', 'رمضان جمال'],
                ['Beni Bachir', 'بني بشير'],
                ['Salah Bouchaour', 'صالح بوشعور'],
                ['Tamalous', 'تمالوس'],
                ['Ain Kechra', 'عين قشرة'],
                ['Oum Toub', 'أم الطوب'],
                ['Bein El Ouiden', 'بين الويدان'],
                ['Fil Fila', 'فلفلة'],
                ['Cheraia', 'الشرايع'],
                ['Kanoua', 'كانوا'],
                ['El Ghedir', 'الغدير'],
                ['Bouchtata', 'بوشطاطة'],
                ['Ouldja Boulbalout', 'الولجة بولبلوط'],
                ['Kheneg Mayoum', 'خنق مايون'],
                ['Hamadi Krouma', 'حمادي كرومة'],
                ['El Marsa', 'المرسى'],
            ],

            'DZ-22' => [
                ['Sidi Bel Abbes', 'سيدي بلعباس'],
                ['Tessala', 'تسالة'],
                ['Sidi Brahim', 'سيدي ابراهيم'],
                ['Mostefa Ben Brahim', 'مصطفى بن ابراهيم'],
                ['Telagh', 'تلاغ'],
                ['Mezaourou', 'مزاورو'],
                ['Boukhanafis', 'بوخنفيس'],
                ['Sidi Ali Boussidi', 'سيدي علي بوسيدي'],
                ['Badredine El Mokrani', 'بدر الدين المقراني'],
                ['Marhoum', 'مرحوم'],
                ['Tafissour', 'تافيسور'],
                ['Amarnas', 'عمارنة'],
                ['Tilmouni', 'تيلاموني'],
                ['Sidi Lahcene', 'سيدي لحسن'],
                ['Ain Thrid', 'عين الثريد'],
                ['Makedra', 'ماقدرة'],
                ['Tenira', 'تنيرة'],
                ['Moulay Slissen', 'مولاي سليسن'],
                ['El Hacaiba', 'الحصيبة'],
                ['Hassi Zehana', 'حاسي زهانة'],
                ['Tabia', 'طابية'],
                ['Merine', 'مرين'],
                ['Ras El Ma', 'رأس الماء'],
                ['Ain Tindamine', 'عين تندمين'],
                ['Ain Kada', 'عين قادة'],
                ['Mcid', 'مسيد'],
                ['Sidi Khaled', 'سيدي خالد'],
                ['Ain El Berd', 'عين البرد'],
                ['Sfissef', 'سفيزف'],
                ['Ain Adden', 'عين عدان'],
                ['Oued Taourira', 'وادي الطويريرة'],
                ['Dhaya', 'الضاية'],
                ['Zerouala', 'زروالة'],
                ['Lamtar', 'لمطار'],
                ['Sidi Chaib', 'سيدي شعيب'],
                ['Sidi Dahou Dezairs', 'سيدي دحو الزاير'],
                ['Oued Sbaa', 'وادي السبع'],
                ['Boudjebaa El Bordj', 'بوجبهة البرج'],
                ['Sehala Thaoura', 'سهالة الثورة'],
                ['Sidi Yacoub', 'سيدي يعقوب'],
                ['Sidi Hamadouche', 'سيدي حمادوش'],
                ['Belarbi', 'بلعربي'],
                ['Oued Sefioun', 'وادي سفيون'],
                ['Teghalimet', 'تغاليمت'],
                ['Ben Badis', 'بن باديس'],
                ['Sidi Ali Benyoub', 'سيدي علي بن يوب'],
                ['Chetouane Belaila', 'شتوان بلايلة'],
                ['Bir El Hammam', 'بئر الحمام'],
                ['Taoudmout', 'تعودموت'],
                ['Redjem Demouche', 'رجم دموش'],
                ['Benachiba Chelia', 'بن شيبة شلية'],
                ['Hassi Dahou', 'حاسي دحو'],
            ],

            'DZ-23' => [
                ['Annaba', 'عنابة'],
                ['Berrahel', 'برحال'],
                ['El Hadjar', 'الحجار'],
                ['Eulma', 'العلمة'],
                ['El Bouni', 'البوني'],
                ['Oued El Aneb', 'وادي العنب'],
                ['Cheurfa', 'الشرفة'],
                ['Seraidi', 'سرايدي'],
                ['Ain Berda', 'عين باردة'],
                ['Chetaibi', 'شطايبي'],
                ['Sidi Amer', 'سيدي عامر'],
                ['Treat', 'تريات'],
            ],

            'DZ-24' => [
                ['Guelma', 'قالمة'],
                ['Nechmaya', 'نشماية'],
                ['Bouati Mahmoud', 'بوعاتي محمود'],
                ['Oued Zenati', 'وادي زناتي'],
                ['Tamlouka', 'تملوكة'],
                ['Oued Fragha', 'وادي فراغة'],
                ['Ain Sandel', 'عين صندل'],
                ['Ras El Agba', 'رأس العقبة'],
                ['Dahouara', 'الضحاورة'],
                ['Belkhir', 'بلخير'],
                ['Ben Djarah', 'بن جراح'],
                ['Bou Hamdane', 'بوحمدان'],
                ['Ain Makhlouf', 'عين مخلوف'],
                ['Ain Ben Beida', 'عين بن بيضاء'],
                ['Khezara', 'خزارة'],
                ['Beni Mezline', 'بني مزلين'],
                ['Bou Hachana', 'بو حشانه'],
                ['Guelaat Bou Sbaa', 'قلعة بوصبع'],
                ['Hammam Maskhoutine', 'حمام مسخوطين'],
                ['El Fedjoudj', 'الفجوج'],
                ['Bordj Sabat', 'برج صباط'],
                ['Hamman Nbail', 'حمام النبائل'],
                ['Ain Larbi', 'عين العربي'],
                ['Medjez Amar', 'مجاز عمار'],
                ['Bouchegouf', 'بوشقوف'],
                ['Heliopolis', 'هيليوبوليس'],
                ['Ain Hessania', 'عين الحساينية'],
                ['Roknia', 'الركنية'],
                ['Salaoua Announa', 'سلاوة عنونة'],
                ['Medjez Sfa', 'مجاز الصفاء'],
                ['Boumahra Ahmed', 'بومهرة أحمد'],
                ['Ain Reggada', 'عين رقادة'],
                ['Oued Cheham', 'وادي الشحم'],
                ['Djeballah Khemissi', 'جبالة خميسى'],
            ],

            'DZ-25' => [
                ['Constantine', 'قسنطينة'],
                ['Hamma Bouziane', 'حامة بوزيان'],
                ['El Haria', 'الحارية'],
                ['Zighoud Youcef', 'زيغود يوسف'],
                ['Didouche Mourad', 'ديدوش مراد'],
                ['El Khroub', 'الخروب'],
                ['Ain Abid', 'عين عبيد'],
                ['Beni Hamiden', 'بني حميدان'],
                ['Ouled Rahmoune', 'أولاد رحمون'],
                ['Ain Smara', 'عين سمارة'],
                ['Mesaoud Boudjeriou', 'مسعود بوجريو'],
                ['Ibn Ziad', 'ابن زياد'],
            ],

            'DZ-26' => [
                ['Medea', 'المدية'],
                ['Ouzera', 'وزرة'],
                ['Ouled Maaref', 'أولاد معارف'],
                ['Ain Boucif', 'عين بوسيف'],
                ['Aissaouia', 'العيساوية'],
                ['Ouled Deide', 'أولاد دايد'],
                ['El Omaria', 'العمارية'],
                ['Derrag', 'دراق'],
                ['El Guelbelkebir', 'القلب الكبير'],
                ['Bouaiche', 'بوعيش'],
                ['Mezerena', 'مزغنة'],
                ['Ouled Brahim', 'أولاد ابراهيم'],
                ['Damiat', 'داميات'],
                ['Sidi Ziane', 'سيدي زيان'],
                ['Tamesguida', 'تامسقيدة'],
                ['El Hamdania', 'الحمدانية'],
                ['Kef Lakhdar', 'الكاف الأخضر'],
                ['Chelalet El Adhaoura', 'شلالة العذاورة'],
                ['Bouskene', 'بوسكن'],
                ['Rebaia', 'الربعية'],
                ['Bouchrahil', 'بوشراحيل'],
                ['Ouled Hellal', 'أولاد هلال'],
                ['Tafraout', 'تافراوت'],
                ['Baata', 'بعطة'],
                ['Boghar', 'بوغار'],
                ['Sidi Naamane', 'سيدي نعمان'],
                ['Ouled Bouachra', 'أولاد بوعشرة'],
                ['Sidi Zahar', 'سيدي الزهار'],
                ['Oued Harbil', 'وادي حربيل'],
                ['Benchicao', 'بن شكاو'],
                ['Sidi Damed', 'سيدي دامد'],
                ['Aziz', 'عزيز'],
                ['Souagui', 'سواقي'],
                ['Zoubiria', 'زبيرية'],
                ['Ksar El Boukhari', 'قصر البخاري'],
                ['El Azizia', 'العزيزية'],
                ['Djouab', 'جواب'],
                ['Chahbounia', 'شهبونية'],
                ['Meghraoua', 'مغراوة'],
                ['Cheniguel', 'شنيقل'],
                ['Ain Ouksir', 'عين أقصير'],
                ['Oum El Djalil', 'أم الجليل'],
                ['Ouamri', 'وامري'],
                ['Si Mahdjoub', 'سي المحجوب'],
                ['Tlatet Eddoair', 'ثلاث دوائر'],
                ['Beni Slimane', 'بني سليمان'],
                ['Berrouaghia', 'برواقية'],
                ['Seghouane', 'سغوان'],
                ['Meftaha', 'مفتاحة'],
                ['Mihoub', 'ميهوب'],
                ['Boughezoul', 'بوغزول'],
                ['Tablat', 'تابلاط'],
                ['Deux Bassins', 'الحوضين'],
                ['Draa Essamar', 'ذراع السمار'],
                ['Sidi Errabia', 'سيدي الربيع'],
                ['Bir Ben Laabed', 'بئر بن العابد'],
                ['El Ouinet', 'الوينات'],
                ['Ouled Antar', 'أولاد عنتر'],
                ['Bouaichoune', 'بوعيشون'],
                ['Hannacha', 'حناشة'],
                ['Sedraia', 'سدراية'],
                ['Medjebar', 'مجبار'],
                ['Khams Djouamaa', 'خمس جوامع'],
                ['Saneg', 'سانق'],
            ],

            'DZ-27' => [
                ['Mostaganem', 'مستغانم'],
                ['Sayada', 'صيادة'],
                ['Fornaka', 'فرناكة'],
                ['Stidia', 'ستيدية'],
                ['Ain Nouissy', 'عين نويسي'],
                ['Hassi Maameche', 'حاسي معماش'],
                ['Ain Tadles', 'عين تادلس'],
                ['Sour', 'سور'],
                ['Oued El Kheir', 'وادي الخير'],
                ['Sidi Bellater', 'سيدي بلعاطر'],
                ['Kheiredine', 'خير الدين'],
                ['Sidi Ali', 'سيدي علي'],
                ['Abdelmalek Ramdane', 'عبد المالك رمضان'],
                ['Hadjadj', 'حجاج'],
                ['Nekmaria', 'نكمارية'],
                ['Sidi Lakhdar', 'سيدي لخضر'],
                ['Achaacha', 'عشعاشة'],
                ['Khadra', 'خضرة'],
                ['Bouguirat', 'بوقيراط'],
                ['Sirat', 'سيرات'],
                ['Ain Sidi Cherif', 'عين سيدي الشريف'],
                ['Mesra', 'ماسرة'],
                ['Mansourah', 'المنصورة'],
                ['Souaflia', 'سوافلية'],
                ['Ouled Boughalem', 'أولاد بوغالم'],
                ['Ouled Maallah', 'أولاد معلة'],
                ['Mezghrane', 'مزغران'],
                ['Ain Boudinar', 'عين بودينار'],
                ['Tazgait', 'تازقايت'],
                ['Safsaf', 'صفصاف'],
                ['Touahria', 'توحيرية'],
                ['El Hassiane', 'الحسيان'],
            ],

            'DZ-28' => [
                ['Msila', 'المسيلة'],
                ['Maadid', 'المعاديد'],
                ['Hammam Dhalaa', 'حمام الضلعة'],
                ['Ouled Derradj', 'أولاد دراج'],
                ['Tarmount', 'تارمقنت'],
                ['Mtarfa', 'المعطرفة'],
                ['Khoubana', 'خبانة'],
                ['Mcif', 'مسيف'],
                ['Chellal', 'شلال'],
                ['Ouled Madhi', 'أولاد ماضي'],
                ['Magra', 'مقرة'],
                ['Berhoum', 'برهوم'],
                ['Ain Khadra', 'عين خضرة'],
                ['Ouled Addi Guebala', 'أولاد عدي لقبالة'],
                ['Belaiba', 'بلعايبة'],
                ['Sidi Aissa', 'سيدي عيسى'],
                ['Ain El Hadjel', 'عين الحجل'],
                ['Sidi Hadjeres', 'سيدي هجرس'],
                ['Ouanougha', 'ونوقة'],
                ['Bou Saada', 'بوعنداس'],
                ['Ouled Sidi Brahim', 'أولاد سيدي ابراهيم'],
                ['Sidi Ameur', 'سيدي عامر'],
                ['Tamsa', 'تامسة'],
                ['Ben Srour', 'بن سرور'],
                ['Ouled Slimane', 'أولاد سليمان'],
                ['El Houamed', 'الهوامد'],
                ['El Hamel', 'الهامل'],
                ['Ouled Mansour', 'أولاد منصور'],
                ['Maarif', 'معريف'],
                ['Dehahna', 'الضحاينة'],
                ['Bouti Sayah', 'بوطي سياح'],
                ['Khettouti Sed Djir', 'خطوطي سد الجير'],
                ['Zarzour', 'زرزور'],
                ['Oued Chair', 'وادي الشاعر'],
                ['Benzouh', 'بن زوح'],
                ['Bir Foda', 'بئر فضة'],
                ['Ain Fares', 'عين فارس'],
                ['Sidi Mhamed', 'سيدي محمد'],
                ['Ouled Atia', 'أولاد عطية'],
                ['Souamaa', 'السوامع'],
                ['Ain El Melh', 'عين الملح'],
                ['Medjedel', 'مجيدل'],
                ['Slim', 'سليم'],
                ['Ain Errich', 'عين الريح'],
                ['Beni Ilmane', 'بني يلمان'],
                ['Oultene', 'ولتانة'],
                ['Djebel Messaad', 'جبل مسعد'],
            ],

            'DZ-29' => [
                ['Mascara', 'معسكر'],
                ['Bou Hanifia', 'بوحنيفية'],
                ['Tizi', 'تيزي'],
                ['Hacine', 'حسين'],
                ['Maoussa', 'ماوسة'],
                ['Teghennif', 'تغنيف'],
                ['El Hachem', 'الحشم'],
                ['Sidi Kada', 'سيدي قادة'],
                ['Zelmata', 'زلمطة'],
                ['Oued El Abtal', 'وادي الأبطال'],
                ['Ain Ferah', 'عين فراح'],
                ['Ghriss', 'غريس'],
                ['Froha', 'فروحة'],
                ['Matemore', 'المطمور'],
                ['Makdha', 'مكدة'],
                ['Sidi Boussaid', 'سيدي بوسعيد'],
                ['El Bordj', 'البرج'],
                ['Ain Fekan', 'عين فكان'],
                ['Benian', 'بنيان'],
                ['Khalouia', 'خلوية'],
                ['El Menaouer', 'المنور'],
                ['Oued Taria', 'وادي التاغية'],
                ['Aouf', 'عوف'],
                ['Ain Fares', 'عين فارس'],
                ['Ain Frass', 'عين فراس'],
                ['Sig', 'سيق'],
                ['Oggaz', 'عقاز'],
                ['Alaimia', 'العلايمية'],
                ['El Gaada', 'القعدة'],
                ['Zahana', 'زهانة'],
                ['Mohammadia', 'المحمدية'],
                ['Sidi Abdelmoumene', 'سيدي عبد المؤمن'],
                ['Ferraguig', 'فرقيق'],
                ['El Ghomri', 'الغمري'],
                ['Sedjerara', 'سجرارة'],
                ['Moctadouz', 'مقدادوز'],
                ['Bou Henni', 'بوحني'],
                ['Guettena', 'قطنة'],
                ['El Mamounia', 'المأمونية'],
                ['El Keurt', 'الكرط'],
                ['Gharrous', 'غروس'],
                ['Gherdjoum', 'غرجوم'],
                ['Chorfa', 'الشرفاء'],
                ['Ras Ain Amirouche', 'رأس عين عميروش'],
                ['Nesmot', 'نصموط'],
                ['Sidi Abdeldjebar', 'سيدي عبد الجبار'],
                ['Sehailia', 'السحايلية'],
            ],

            'DZ-30' => [
                ['Ouargla', 'ورقلة'],
                ['Ain Beida', 'عين البيضاء'],
                ['Ngoussa', 'نقوسة'],
                ['Hassi Messaoud', 'حاسي مسعود'],
                ['Rouissat', 'الرويسات'],
                ['Balidat Ameur', 'بلدة عامر'],
                ['Tebesbest', 'تبسبست'],
                ['Nezla', 'النزلة'],
                ['Zaouia El Abidia', 'الزاوية العابدية'],
                ['Sidi Slimane', 'سيدي سليمان'],
                ['Sidi Khouiled', 'سيدي خويلد'],
                ['Hassi Ben Abdellah', 'حاسي بن عبد الله'],
                ['Touggourt', 'تقرت'],
                ['El Hadjira', 'الحجيرة'],
                ['Taibet', 'الطيبات'],
                ['Tamacine', 'تماسين'],
                ['Benaceur', 'بن ناصر'],
                ['Mnaguer', 'المنقر'],
                ['Megarine', 'المقارين'],
                ['El Allia', 'العالية'],
                ['El Borma', 'البورمة'],
            ],

            'DZ-31' => [
                ['Oran', 'وهران'],
                ['Gdyel', 'قديل'],
                ['Bir El Djir', 'بئر الجير'],
                ['Hassi Bounif', 'حاسي بونيف'],
                ['Es Senia', 'السانية'],
                ['Arzew', 'أرزيو'],
                ['Bethioua', 'بطيوة'],
                ['Marsat El Hadjadj', 'مرسى الحجاج'],
                ['Ain Turk', 'عين الترك'],
                ['El Ancar', 'العنصر'],
                ['Oued Tlelat', 'وادي تليلات'],
                ['Tafraoui', 'طفراوي'],
                ['Sidi Chami', 'سيدي الشحمي'],
                ['Boufatis', 'بوفاطيس'],
                ['Mers El Kebir', 'المرسى الكبير'],
                ['Bousfer', 'بوسفر'],
                ['El Karma', 'الكرمة'],
                ['El Braya', 'البراية'],
                ['Hassi Ben Okba', 'حاسي بن عقبة'],
                ['Ben Freha', 'بن فريحة'],
                ['Hassi Mefsoukh', 'حاسي مفسوخ'],
                ['Sidi Ben Yabka', 'سيدي بن يبكة'],
                ['Messerghin', 'مسرغين'],
                ['Boutlelis', 'بوتليليس'],
                ['Ain Kerma', 'عين الكرمة'],
                ['Ain Biya', 'عين البية'],
            ],

            'DZ-32' => [
                ['El Bayadh', 'البيض'],
                ['Rogassa', 'رقاصة'],
                ['Stitten', 'ستيتن'],
                ['Brezina', 'بريزينة'],
                ['Ghassoul', 'الغاسول'],
                ['Boualem', 'بوعلام'],
                ['El Abiodh Sidi Cheikh', 'الأبيض سيدي الشيخ'],
                ['Ain El Orak', 'عين العراك'],
                ['Arbaouat', 'الأربوات'],
                ['Bougtoub', 'بوقطب'],
                ['El Kheither', 'الخَيثر'],
                ['Kef El Ahmar', 'الكاف الأحمر'],
                ['Boussemghoun', 'بوسمغون'],
                ['Chellala', 'شلالة'],
                ['Krakda', 'كراكدة'],
                ['El Bnoud', 'البنود'],
                ['Cheguig', 'الشقيق'],
                ['Sidi Ameur', 'سيدي عامر'],
                ['El Mehara', 'المهارة'],
                ['Tousmouline', 'توسمولين'],
                ['Sidi Slimane', 'سيدي سليمان'],
                ['Sidi Tifour', 'سيدي الطيفور'],
            ],

            'DZ-33' => [
                ['Illizi', 'إليزي'],
                ['Djanet', 'جانت'],
                ['Debdeb', 'دبدب'],
                ['Bordj Omar Driss', 'برج عمر إدريس'],
                ['Bordj El Haouasse', 'برج الحواس'],
                ['In Amenas', 'إن أميناس'],
            ],

            'DZ-34' => [
                ['Bordj Bou Arreridj', 'برج بوعريريج'],
                ['Ras El Oued', 'رأس الواد'],
                ['Bordj Zemoura', 'برج زمورة'],
                ['Mansoura', 'المنصورة'],
                ['El Mhir', 'المهير'],
                ['Ben Daoud', 'بن داود'],
                ['El Achir', 'العشير'],
                ['Ain Taghrout', 'عين تاغروت'],
                ['Bordj Ghdir', 'برج الغدير'],
                ['Sidi Embarek', 'سيدي مبارك'],
                ['El Hamadia', 'الحمادية'],
                ['Belimour', 'بليمور'],
                ['Medjana', 'مجّانة'],
                ['Teniet En Nasr', 'ثنية النصر'],
                ['Djaafra', 'جعافرة'],
                ['El Main', 'الماين'],
                ['Ouled Brahem', 'أولاد ابراهم'],
                ['Ouled Dahmane', 'أولاد دحمان'],
                ['Hasnaoua', 'حسناوة'],
                ['Khelil', 'خليل'],
                ['Taglait', 'تقلات'],
                ['Ksour', 'القصور'],
                ['Ouled Sidi Brahim', 'أولاد سيدي إبراهيم'],
                ['Tafreg', 'تافرا'],
                ['Colla', 'قلا'],
                ['Tixter', 'تيكستر'],
                ['El Ach', 'العاش'],
                ['El Anseur', 'العناصر'],
                ['Tesmart', 'تسمرت'],
                ['Ain Tesra', 'عين تسرة'],
                ['Bir Kasdali', 'بئر قاصد علي'],
                ['Ghilassa', 'غيلاسة'],
                ['Rabta', 'الرابطة'],
                ['Haraza', 'حرازة'],
            ],

            'DZ-35' => [
                ['Boumerdes', 'بومرداس'],
                ['Boudouaou', 'بودواو'],
                ['Afir', 'أفراح'],
                ['Bordj Menaiel', 'برج منايل'],
                ['Baghlia', 'بغلية'],
                ['Sidi Daoud', 'سيدي داود'],
                ['Naciria', 'ناصرية'],
                ['Djinet', 'جنات'],
                ['Isser', 'يسر'],
                ['Zemmouri', 'زموري'],
                ['Si Mustapha', 'سي مصطفى'],
                ['Tidjelabine', 'تيجلابين'],
                ['Chabet El Ameur', 'شعبة العامر'],
                ['Thenia', 'الثنية'],
                ['Timezrit', 'تيمزريت'],
                ['Corso', 'قورصو'],
                ['Ouled Moussa', 'أولاد موسى'],
                ['Larbatache', 'الأربعطاش'],
                ['Bouzegza Keddara', 'بوزقزة قدارة'],
                ['Taourga', 'تاورقة'],
                ['Ouled Aissa', 'أولاد عيسى'],
                ['Ben Choud', 'بن شود'],
                ['Dellys', 'دلس'],
                ['Ammal', 'عمال'],
                ['Beni Amrane', 'بني عمران'],
                ['Souk El Had', 'سوق الحد'],
                ['Boudouaou El Bahri', 'بودواو البحري'],
                ['Ouled Hedadj', 'أولاد هداج'],
                ['Laghata', 'لقاطة'],
                ['Hammedi', 'حمادي'],
                ['Khemis El Khechna', 'خميس الخشنة'],
                ['El Kharrouba', 'الخروبة'],
            ],

            'DZ-36' => [
                ['El Tarf', 'الطارف'],
                ['Bouhadjar', 'بوحجار'],
                ['Ben Mhidi', 'بن مهيدي'],
                ['Bougous', 'بوغوص'],
                ['El Kala', 'القالة'],
                ['Ain El Assel', 'عين العسل'],
                ['El Aioun', 'العيون'],
                ['Bouteldja', 'بوثلجة'],
                ['Souarekh', 'السوارخ'],
                ['Berrihane', 'بريحان'],
                ['Lac Des Oiseaux', 'بحيرة الطيور'],
                ['Chefia', 'الشافية'],
                ['Drean', 'الذرّاع'],
                ['Chihani', 'الشيهاني'],
                ['Chebaita Mokhtar', 'شبايطة مختار'],
                ['Besbes', 'بسباس'],
                ['Asfour', 'عصفور'],
                ['Echatt', 'الشط'],
                ['Zerizer', 'الزريريز'],
                ['Zitouna', 'الزيتونة'],
                ['Ain Kerma', 'عين الكرمة'],
                ['Oued Zitoun', 'وادي الزيتون'],
                ['Hammam Beni Salah', 'حمام بني صالح'],
                ['Raml Souk', 'رمل السوق'],
            ],

            'DZ-37' => [
                ['Tindouf', 'تندوف'],
                ['Oum El Assel', 'أم العسل'],
            ],

            'DZ-38' => [
                ['Tissemsilt', 'تيسمسيلت'],
                ['Bordj Bou Naama', 'برج بونعامة'],
                ['Theniet El Had', 'ثنية الأحد'],
                ['Lazharia', 'الأزهرية'],
                ['Beni Chaib', 'بني شعيب'],
                ['Lardjem', 'الأربعاء'],
                ['Melaab', 'الملعب'],
                ['Sidi Lantri', 'سيدي العنتري'],
                ['Bordj El Emir Abdelkader', 'برج الأمير عبد القادر'],
                ['Layoune', 'العيون'],
                ['Khemisti', 'خميستي'],
                ['Ouled Bessem', 'أولاد بسام'],
                ['Ammari', 'عماري'],
                ['Youssoufia', 'اليوسفية'],
                ['Sidi Boutouchent', 'سيدي بوتوشنت'],
                ['Larbaa', 'الأرباع'],
                ['Maasem', 'المعاصم'],
                ['Sidi Abed', 'سيدي عابد'],
                ['Tamalaht', 'تمالحت'],
                ['Sidi Slimane', 'سيدي سليمان'],
                ['Boucaid', 'بوقايد'],
                ['Beni Lahcene', 'بني لحسن'],
            ],

            'DZ-39' => [
                ['El Oued', 'الوادي'],
                ['Robbah', 'الرباح'],
                ['Oued El Alenda', 'وادي العلندة'],
                ['Bayadha', 'البياضة'],
                ['Nakhla', 'النخلة'],
                ['Guemar', 'قمار'],
                ['Kouinine', 'كوينين'],
                ['Reguiba', 'الرقيبة'],
                ['Hamraia', 'الحمراية'],
                ['Taghzout', 'تغزوت'],
                ['Debila', 'دبيلة'],
                ['Hassani Abdelkrim', 'حساني عبد الكريم'],
                ['Hassi Khelifa', 'حاسي خليفة'],
                ['Taleb Larbi', 'طالب العربي'],
                ['Douar El Ma', 'دوار الماء'],
                ['Sidi Aoun', 'سيدي عون'],
                ['Trifaoui', 'تريفاو'],
                ['Magrane', 'المقرن'],
                ['Beni Guecha', 'بني قشة'],
                ['Ourmas', 'ورماس'],
                ['Still', 'سطيل'],
                ['Mrara', 'مرار'],
                ['Sidi Khellil', 'سيدي خليل'],
                ['Tendla', 'تندلة'],
                ['El Ogla', 'العقلة'],
                ['Mih Ouansa', 'ميه وانسة'],
                ['El Mghair', 'المغير'],
                ['Djamaa', 'جامعة'],
                ['Oum Touyour', 'أم الطيور'],
                ['Sidi Amrane', 'سيدي عمران'],
            ],

            'DZ-40' => [
                ['Khenchela', 'خنشلة'],
                ['Mtoussa', 'متوسة'],
                ['Kais', 'قايس'],
                ['Baghai', 'بغاي'],
                ['El Hamma', 'الحمّة'],
                ['Ain Touila', 'عين التويلة'],
                ['Taouzianat', 'تاوزيانت'],
                ['Bouhmama', 'بوحمامة'],
                ['El Oueldja', 'الولجة'],
                ['Remila', 'الرميلة'],
                ['Cherchar', 'شرشار'],
                ['Djellal', 'جلال'],
                ['Babar', 'بابار'],
                ['Tamza', 'تمزّة'],
                ['Ensigha', 'إنسيغة'],
                ['Ouled Rechache', 'أولاد رشاش'],
                ['El Mahmal', 'المحمل'],
                ['Msara', 'مصارة'],
                ['Yabous', 'يابوس'],
                ['Khirane', 'الخيران'],
                ['Chelia', 'الشلية'],
            ],

            'DZ-41' => [
                ['Souk Ahras', 'سوق أهراس'],
                ['Sedrata', 'سدراتة'],
                ['Hanancha', 'الحنانشة'],
                ['Mechroha', 'المشروحة'],
                ['Ouled Driss', 'أولاد إدريس'],
                ['Tiffech', 'تيفاش'],
                ['Zaarouria', 'الزعروية'],
                ['Taoura', 'تاورة'],
                ['Drea', 'الدريعة'],
                ['Haddada', 'الحدادة'],
                ['Khedara', 'الخضارة'],
                ['Merahna', 'المراهنة'],
                ['Ouled Moumen', 'أولاد مؤمن'],
                ['Bir Bouhouche', 'بئر بوحوش'],
                ['Mdaourouche', 'مدوروش'],
                ['Oum El Adhaim', 'أم العظايم'],
                ['Ain Zana', 'عين الزانة'],
                ['Ain Soltane', 'عين سلطان'],
                ['Quillen', 'الكليلن'],
                ['Sidi Fredj', 'سيدي فرج'],
                ['Safel El Ouiden', 'سافل الوديان'],
                ['Ragouba', 'الرقوبة'],
                ['Khemissa', 'خميسة'],
                ['Oued Keberit', 'وادي الكبريت'],
                ['Terraguelt', 'ترقيلت'],
                ['Zouabi', 'الزوابي'],
            ],

            'DZ-42' => [
                ['Tipaza', 'تيبازة'],
                ['Menaceur', 'مناصر'],
                ['Larhat', 'الأرهاط'],
                ['Douaouda', 'دواودة'],
                ['Bourkika', 'بورقيقة'],
                ['Khemisti', 'خميستي'],
                ['Aghabal', 'أغبال'],
                ['Hadjout', 'حجوط'],
                ['Sidi Amar', 'سيدي عامر'],
                ['Gouraya', 'قوراية'],
                ['Nodor', 'الناظور'],
                ['Chaiba', 'الشعيبة'],
                ['Ain Tagourait', 'عين تاقوريت'],
                ['Cherchel', 'شرشال'],
                ['Damous', 'داموس'],
                ['Meurad', 'موراد'],
                ['Fouka', 'فوكة'],
                ['Bou Ismail', 'بواسماعيل'],
                ['Ahmer El Ain', 'أحمر العين'],
                ['Bou Haroun', 'بوهارون'],
                ['Sidi Ghiles', 'سيدي غيلاس'],
                ['Messelmoun', 'مسلمون'],
                ['Sidi Rached', 'سيدي راشد'],
                ['Kolea', 'القليعة'],
                ['Attatba', 'الحطاطبة'],
                ['Sidi Semiane', 'سيدي سميان'],
                ['Beni Milleuk', 'بني ميلوك'],
                ['Hadjerat Ennous', 'حجرة النص'],
            ],

            'DZ-43' => [
                ['Mila', 'ميلة'],
                ['Ferdjioua', 'فرجيوة'],
                ['Chelghoum Laid', 'شلغوم العيد'],
                ['Oued Athmenia', 'وادي العثمانية'],
                ['Ain Mellouk', 'عين ملوك'],
                ['Telerghma', 'تلاغمة'],
                ['Oued Seguen', 'وادي سقان'],
                ['Tadjenanet', 'تاجنانت'],
                ['Benyahia Abderrahmane', 'بن يحيى عبد الرحمن'],
                ['Oued Endja', 'وادي النجاء'],
                ['Ahmed Rachedi', 'أحمد راشدي'],
                ['Ouled Khalouf', 'أولاد خلوف'],
                ['Tiberguent', 'تيبرغنت'],
                ['Bouhatem', 'بوحاتم'],
                ['Rouached', 'رواشد'],
                ['Tessala Lamatai', 'تسالة لمطاعي'],
                ['Grarem Gouga', 'غرارم قوقة'],
                ['Sidi Merouane', 'سيدي مروان'],
                ['Tassadane Haddada', 'تسدان حدادة'],
                ['Derradji Bousselah', 'درّاجي بوسلاح'],
                ['Minar Zarza', 'مينار زرزة'],
                ['Amira Arras', 'عميرة أراس'],
                ['Terrai Bainen', 'ترعي باينان'],
                ['Hamala', 'حمالة'],
                ['Ain Tine', 'عين التين'],
                ['El Mechira', 'المشيرة'],
                ['Sidi Khelifa', 'سيدي خليفة'],
                ['Zeghaia', 'زغاية'],
                ['Elayadi Barbes', 'العيادي برباس'],
                ['Ain Beida Harriche', 'عين البيضاء حريش'],
                ['Yahia Beniguecha', 'يحيى بن إيقيشة'],
                ['Chigara', 'شيقارة'],
            ],

            'DZ-44' => [
                ['Ain Defla', 'عين الدفلى'],
                ['Miliana', 'مليانة'],
                ['Boumedfaa', 'بومدفع'],
                ['Khemis Miliana', 'خميس مليانة'],
                ['Hammam Righa', 'حمام ريغة'],
                ['Arib', 'عريب'],
                ['Djelida', 'جليدة'],
                ['El Amra', 'العمرة'],
                ['Bourached', 'بوراشد'],
                ['El Attaf', 'العطاف'],
                ['El Abadia', 'العبادية'],
                ['Djendel', 'جندل'],
                ['Oued Chorfa', 'وادي الشرفاء'],
                ['Ain Lechiakh', 'عين الاشياخ'],
                ['Oued Djemaa', 'وادي الجمعة'],
                ['Rouina', 'روينة'],
                ['Zeddine', 'زدين'],
                ['El Hassania', 'الحسانية'],
                ['Bir Ouled Khelifa', 'بئر أولاد خليفة'],
                ['Ain Soltane', 'عين سلطان'],
                ['Tarik Ibn Ziad', 'طارق بن زياد'],
                ['Bordj Emir Khaled', 'برج الأمير خالد'],
                ['Ain Torki', 'عين التركي'],
                ['Sidi Lakhdar', 'سيدي الأخضر'],
                ['Ben Allal', 'بن علال'],
                ['Ain Benian', 'عين بنيان'],
                ['Hoceinia', 'الوسينية'],
                ['Barbouche', 'بربوش'],
                ['Djemaa Ouled Chikh', 'جمعة أولاد الشيخ'],
                ['Mekhatria', 'مخاطرية'],
                ['Bathia', 'بطحية'],
                ['Tachta Zegagha', 'تحتة زقاغة'],
                ['Ain Bouyahia', 'عين بويحيى'],
                ['El Maine', 'الماين'],
                ['Tiberkanine', 'تيبركانين'],
                ['Belaas', 'بلعاص'],
            ],

            'DZ-45' => [
                ['Naama', 'النعامة'],
                ['Mechria', 'المشرية'],
                ['Ain Sefra', 'عين الصفراء'],
                ['Tiout', 'تيوت'],
                ['Sfissifa', 'سفيسيفة'],
                ['Moghrar', 'مغرار'],
                ['Assela', 'عسلة'],
                ['Djeniane Bourzeg', 'جنان بوزق'],
                ['Ain Ben Khelil', 'عين بن خليل'],
                ['Makman Ben Amer', 'مكمن بن عمار'],
                ['Kasdir', 'القصدير'],
                ['El Biod', 'البيوض'],
            ],

            'DZ-46' => [
                ['Ain Temouchent', 'عين تموشنت'],
                ['Chaabet El Ham', 'شعبة اللحم'],
                ['Ain Kihal', 'عين الكيحل'],
                ['Hammam Bouhadjar', 'حمام بوحجر'],
                ['Bou Zedjar', 'بوزجار'],
                ['Oued Berkeche', 'وادي برقش'],
                ['Aghlal', 'أغلال'],
                ['Terga', 'تارقة'],
                ['Ain El Arbaa', 'عين الأرباع'],
                ['Tamzoura', 'تامزورة'],
                ['Chentouf', 'شنتوف'],
                ['Sidi Ben Adda', 'سيدي بن عدة'],
                ['Aoubellil', 'عوبليل'],
                ['El Malah', 'الملاح'],
                ['Sidi Boumediene', 'سيدي بومدين'],
                ['Oued Sabah', 'وادي صباح'],
                ['Ouled Boudjemaa', 'أولاد بوجمعة'],
                ['Ain Tolba', 'عين الطلبة'],
                ['El Amria', 'العامرية'],
                ['Hassi El Ghella', 'حاسي الغلة'],
                ['Hassasna', 'الحساسنة'],
                ['Ouled Kihal', 'أولاد الكيحل'],
                ['Beni Saf', 'بني صاف'],
                ['Sidi Safi', 'سيدي صافي'],
                ['Oulhaca El Gheraba', 'ولهاصة الغرابة'],
                ['Tadmaya', 'تادماية'],
                ['El Emir Abdelkader', 'الأمير عبد القادر'],
                ['El Messaid', 'المساعيد'],
            ],

            'DZ-47' => [
                ['Ghardaia', 'غرداية'],
                ['El Meniaa', 'المنيعة'],
                ['Dhayet Bendhahoua', 'ضاية بن ضحوة'],
                ['Berriane', 'بريان'],
                ['Metlili', 'متليلي'],
                ['El Guerrara', 'القرارة'],
                ['El Atteuf', 'العطف'],
                ['Zelfana', 'زلفانة'],
                ['Sebseb', 'سبسب'],
                ['Bounoura', 'بونورة'],
                ['Hassi Fehal', 'حاسي الفحل'],
                ['Hassi Gara', 'حاسي قارة'],
                ['Mansoura', 'المنصورة'],
            ],

            'DZ-48' => [
                ['Relizane', 'غليزان'],
                ['Oued Rhiou', 'وادي رهيو'],
                ['Belaassel Bouzegza', 'بلعسل بوزقزة'],
                ['Sidi Saada', 'سيدي السعداء'],
                ['Ouled Aiche', 'أولاد عيش'],
                ['Sidi Lazreg', 'سيدي لازرق'],
                ['El Hamadna', 'الحمادنة'],
                ['Sidi Mhamed Ben Ali', 'سيدي محمد بن علي'],
                ['Mediouna', 'مديونة'],
                ['Sidi Khettab', 'سيدي خطاب'],
                ['Ammi Moussa', 'عمي موسى'],
                ['Zemmoura', 'زمورة'],
                ['Beni Dergoun', 'بني درقون'],
                ['Djidiouia', 'جديوية'],
                ['El Guettar', 'القطار'],
                ['Hamri', 'الحمري'],
                ['El Matmar', 'المطمر'],
                ['Sidi Mhamed Ben Aouda', 'سيدي محمد بن عودة'],
                ['Ain Tarek', 'عين طارق'],
                ['Oued Essalem', 'وادي السلام'],
                ['Ouarizane', 'وارزان'],
                ['Mazouna', 'مازونة'],
                ['Kalaa', 'القلعة'],
                ['Ain Rahma', 'عين الرحمة'],
                ['Yellel', 'يلل'],
                ['Oued El Djemaa', 'وادي الجمعة'],
                ['Ramka', 'رمكة'],
                ['Mendes', 'منداس'],
                ['Lahlef', 'لحلاف'],
                ['Beni Zentis', 'بني زنطيس'],
                ['Souk El Haad', 'سوق الحد'],
                ['Dar Ben Abdellah', 'دار بن عبد الله'],
                ['El Hassi', 'الحاسي'],
                ['Had Echkalla', 'حاد إشكالة'],
                ['Bendaoud', 'بن داود'],
                ['El Ouldja', 'الولجة'],
                ['Merdja Sidi Abed', 'مرجة سيدي عابد'],
                ['Ouled Sidi Mihoub', 'أولاد سيدي مهيوب'],
            ],

            'DZ-49' => [
                ['Timimoun', 'تيميمون'],
                ['Charouine', 'شروين'],
                ['Ksar Kaddour', 'قصر قدور'],
                ['Ouled Said', 'أولاد سعيد'],
                ['Tinerkouk', 'تينركوك'],
                ['Deldoul', 'دلدول'],
                ['Metarfa', 'المطرفة'],
                ['Aougrout', 'أوقروت'],
                ['Talmine', 'تالمين'],
                ['Ouled Aissa', 'أولاد عيسى'],
            ],

            'DZ-50' => [
                ['B Badji Mokhtar', 'ب. باجي مختار'],
                ['Timiaouine', 'تيمياوين'],
            ],

            'DZ-51' => [
                ['Ouled Djellal', 'أولاد جلال'],
                ['Sidi Khaled', 'سيدي خالد'],
                ['Ras El Miad', 'رأس الميعاد'],
                ['Besbes', 'بسباس'],
                ['Chaiba', 'الشعيبة'],
                ['Doucen', 'الدوسن'],
            ],

            'DZ-52' => [
                ['Beni Abbes', 'بني عباس'],
                ['Tamtert', 'تامترت'],
                ['Kerzaz', 'كرزاز'],
                ['Timoudi', 'تيمودي'],
                ['Beni Ikhlef', 'بني يخلف'],
                ['El Ouata', 'الوَطَة'],
                ['Tabelbala', 'تبلبالة'],
                ['Ouled Khoudir', 'أولاد خضير'],
                ['Ksabi', 'القصابي'],
                ['Igli', 'إقلي'],
            ],

            'DZ-53' => [
                ['In Salah', 'عين صالح'],
                ['In Ghar', 'عين غار'],
                ['Foggaret Azzaouia', 'فُقَارَتْ الزاوية'],
            ],

            'DZ-54' => [
                ['In Guezzam', 'عين قزام'],
                ['Tinzaouatine', 'تنزواتين'],
            ],

            'DZ-55' => [
                ['Touggourt', 'تقرت'],
                ['Nezla', 'النزلة'],
                ['Tebesbest', 'تبسبست'],
                ['Zaouia El Abidia', 'الزاوية العابدية'],
                ['Temacine', 'تماسين'],
                ['Blidet Amor', 'بلدية عامر'],
                ['Megarine', 'المقارين'],
                ['Mnaguer', 'المنقر'],
                ['Taibet', 'الطيبات'],
                ['Benaceur', 'بن ناصر'],
                ['Sidi Slimane', 'سيدي سليمان'],
                ['El-hadjira', 'الحجيرة'],
                ['El Alia', 'العالية'],
            ],

            'DZ-56' => [
                ['Djanet', 'جانت'],
                ['Bordj El Haouasse', 'برج الحواس'],
            ],

            'DZ-57' => [
                ['El-mghair', 'المغير'],
                ['Oum Touyour', 'أم الطيور'],
                ['Still', 'سطيل'],
                ['Sidi Khelil', 'سيدي خليل'],
                ['Djamaa', 'جامعة'],
                ['Sidi Amrane', 'سيدي عمران'],
                ['Tenedla', 'تندلة'],
                ['Mrara', 'مرار'],
            ],

            'DZ-58' => [
                ['El Meniaa', 'المنيعة'],
                ['Hassi Gara', 'حاسي قارة'],
                ['Hassi Fehal', 'حاسي الفحل'],
            ],

        ];

        foreach ($communes as $code => $list) {
            $wilayaId = Wilaya::where('code', $code)->value('id');

            if ($wilayaId) {
                foreach ($list as [$name_en, $name_ar]) {
                    Commune::create([
                        'wilaya_id' => $wilayaId,
                        'name_en'   => $name_en,
                        'name_ar'   => $name_ar,
                    ]);
                }
            }
        }
    }
}
